version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql/data
  auth:
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - DBHOST=postgres
      - DBNAME=auth
    depends_on:
      - postgres
    container_name: auth